### ISSUE TITLE
Different result using annotate_OT or annotate

### ISSUE THREAD

**Issue by QuanlongJiang** [simonwm/tacco#16]
Dear author,
I test the annotate and the annotate_OT, but their results were very different. The annotate_OT result is better according to the priori knowledge. So I want to known why they are different and how to choose the better method.

`tc.tl.annotate(adata, ref, method='OT',result_key='TACCO',annotation_key='cell_type',assume_valid_counts=True)`
`df = tc.tl.annotate_OT(adata, ref,annotation_key='cell_type')`

Looking forward to your reply, and thank you in advance.

quanlong

**Comment by JWatter** [comment]
Hi,

the `tc.tl.annotate` with `method='OT'` indeed calls `tc.tl.annotate_OT` internally (actually with an internal version of it). But before it does so, it does extra things, like wrapping it with additional functionality.

You can disable most that explicitly, e.g., by adding `bisections = 0`, `platform_iterations = -1`, `remove_constant_genes = False` to the arguments of `tc.tl.annotate`.

What choice of parameters is the best is depending on your use case. If you have strong reason to believe that the prior knowledge is correct, then a choice of parameters that reproduces this more might make sense. For that you might want to tune the `lamb` parameter of `tc.tl.annotate_OT` (which is also understood by `tc.tl.annotate` with `method='OT'`).

Another difference between the two function call is in the priors:
`tc.tl.annotate_OT` uses a flat prior over celltypes, while `tc.tl.annotate` uses a prior that takes the cell type proportions of the reference into account.

So in order to produce the same output as `tc.tl.annotate_OT` with `tc.tl.annotate`, you would have to create a flat prior for annotate, e.g., with
`prior = pd.Series({ct:1 for ct in adata_ref.obs['celltype'].unique()})` and then call annotate like
`df = tc.tl.annotate(adata, adata_ref, annotation_key='celltype', method='OT', bisections = 0, platform_iterations = -1, remove_constant_genes = False, annotation_prior = prior)`

In general, we recommend to use `tc.tl.annotate` with appropriate parameters as it is more flexible. In our experience the default behavior works quite well in many cases, but in most cases the performance can be further improved by tuning parameters.

I hope this helps!
