### ISSUE TITLE
Question - can TACCO examine regions of a Visium slide

### ISSUE THREAD

**Issue by cathalgking** [simonwm/tacco#7]
I am analysing a 10x Visium dataset and I would like to examine 2 different areas or regions of the same Visium slide (image below). The data is from a mouse colon and some of the tissue is tumour and some is not. We would like to examine and compare the spots / genes in both regions (tumour vs non). 
Can TACCO assist with this task?
Thanks
![Visium_Mouse_Patholo](https://user-images.githubusercontent.com/32261323/235338068-c0841ff7-ae83-408d-acf0-058173188c8a.png)

**Comment by simonwm** [comment]
Yes, it can.
It seems that you have the two regions already annotated. Then you could use [tacco.tools.enrichments](https://simonwm.github.io/tacco/_autosummary/tacco.tools.enrichments.html) to get lists of potentially interesting genes for the two regions and after that [tacco.tools.setup_goa_analysis](https://simonwm.github.io/tacco/_autosummary/tacco.tools.setup_goa_analysis.html) and [tacco.tools.run_goa_analysis](https://simonwm.github.io/tacco/_autosummary/tacco.tools.run_goa_analysis.html) to get pointers about potentially interesting biology that is going on.
You could also check out the [examples](https://simonwm.github.io/tacco/examples.html) in particular [slideseq_mouse_colon](https://simonwm.github.io/tacco/notebooks/slideseq_mouse_colon.html) for additional ideas about what analyses you might want to do with your data. While there are no Visium examples in the documentation, yet, the Slide-Seq based examples should be informative, as they also cover the analysis of spatial expression data on pixels.
I hope this helps!

**Comment by cathalgking** [comment]
Ok, but the regions I have annotated is just a drawing - drawn on by a pathologist. Can I input co-ordinates of those areas in the enrichments function? thanks

**Comment by simonwm** [comment]
Not in the enrichments function.
Making drawings machine-readable is nothing which tacco can help you with. But as you suggested using coordinates, which sounds quite manual anyway: You could identify a few "seed" observations via their coordinates, mark them manually in an obs column of your Anndata object and fill the remaining observations using the spatially nearest "seed" observations with [tacco.tools.fill_regions](https://simonwm.github.io/tacco/_autosummary/tacco.tools.fill_regions.html), basically expanding the annotation manually with a Voronoi diagram of the number of "seed" observations.
But as it works with regular Anndata objects, you can use your favorite method to attach this information to the Visium dataset. As soon as you have regions annotated in the dataset, you can use them for enrichment.
Alternatively you can create regions data-driven instead of pathologist-driven using the [tacco.tools.find_regions](https://simonwm.github.io/tacco/_autosummary/tacco.tools.find_regions.html).
